extension ShowcaseCommands {
  static let start = CommandSpecification(
    unportedPath: ["showcase", "start"],
    command: "showcase.start",
    summary: "Start a showcase run from a plan file or an ad hoc selection.",
    flags: [
      CommonFlags.repository,
      CommonFlags.dataRoot,
      CommonFlags.component,
      CommonFlags.json,
      FlagSpecification(
        key: "planFile",
        name: "--plan-file",
        kind: .string,
        summary: "Plan file to start the run from (inside the workspace).",
        valueName: "<path>",
      ),
      FlagSpecification(
        key: "adhoc",
        name: "--adhoc",
        kind: .boolean,
        summary: "Build an ad hoc plan instead of reading --plan-file.",
      ),
      FlagSpecification(
        key: "select",
        name: "--select",
        kind: .string,
        summary: "Use-case id to select for the ad hoc plan.",
        valueName: "<id>",
      ),
      FlagSpecification(
        key: "audience",
        name: "--audience",
        kind: .string,
        summary: "Ad hoc plan audience (defaults to reviewer).",
        valueName: "<audience>",
      ),
      FlagSpecification(
        key: "timebox",
        name: "--timebox",
        kind: .integer,
        summary: "Ad hoc plan timebox in seconds (defaults to 600).",
        valueName: "<seconds>",
      ),
      FlagSpecification(
        key: "generatedAt",
        name: "--generated-at",
        kind: .string,
        summary: "Ad hoc plan generation timestamp.",
        valueName: "<iso>",
      ),
      ShowcaseFlags.idempotencyKey,
      FlagSpecification(
        key: "recordedAt",
        name: "--recorded-at",
        kind: .string,
        summary: "Recorded-at timestamp for the start event.",
        valueName: "<iso>",
      ),
    ],
    subrow: "4e",
  )

  static let recordObservation = CommandSpecification(
    unportedPath: ["showcase", "record-observation"],
    command: "showcase.record-observation",
    summary: "Append an observation to a showcase run plan item.",
    flags: [
      CommonFlags.repository,
      CommonFlags.dataRoot,
      CommonFlags.component,
      CommonFlags.json,
      ShowcaseFlags.run,
      ShowcaseFlags.item,
      FlagSpecification(
        key: "text",
        name: "--text",
        kind: .string,
        summary: "Observation text.",
        valueName: "<text>",
        isRequired: true,
      ),
      ShowcaseFlags.idempotencyKey,
      FlagSpecification(
        key: "recordedAt",
        name: "--recorded-at",
        kind: .string,
        summary: "Recorded-at timestamp for the observation event.",
        valueName: "<iso>",
      ),
    ],
    subrow: "4e",
  )

  static let recordVerdict = CommandSpecification(
    unportedPath: ["showcase", "record-verdict"],
    command: "showcase.record-verdict",
    summary: "Append a verdict to a showcase run plan item.",
    flags: [
      CommonFlags.repository,
      CommonFlags.dataRoot,
      CommonFlags.component,
      CommonFlags.json,
      ShowcaseFlags.run,
      ShowcaseFlags.item,
      FlagSpecification(
        key: "verdict",
        name: "--verdict",
        kind: .string,
        summary: "Verdict value.",
        valueName: "<verdict>",
        isRequired: true,
      ),
      ShowcaseFlags.actor,
      ShowcaseFlags.idempotencyKey,
      FlagSpecification(
        key: "recordedAt",
        name: "--recorded-at",
        kind: .string,
        summary: "Recorded-at timestamp for the verdict event.",
        valueName: "<iso>",
      ),
    ],
    subrow: "4e",
  )

  static let decide = CommandSpecification(
    unportedPath: ["showcase", "decide"],
    command: "showcase.decide",
    summary: "Record a failure decision against a showcase verdict event.",
    flags: [
      CommonFlags.repository,
      CommonFlags.dataRoot,
      CommonFlags.component,
      CommonFlags.json,
      ShowcaseFlags.run,
      FlagSpecification(
        key: "verdictEvent",
        name: "--verdict-event",
        kind: .string,
        summary: "Verdict event id the decision targets.",
        valueName: "<event-id>",
        isRequired: true,
      ),
      FlagSpecification(
        key: "decision",
        name: "--decision",
        kind: .string,
        summary: "Decision value.",
        valueName: "<decision>",
        isRequired: true,
      ),
      FlagSpecification(
        key: "reason",
        name: "--reason",
        kind: .string,
        summary: "Why the decision was made.",
        valueName: "<text>",
        isRequired: true,
      ),
      ShowcaseFlags.actor,
      ShowcaseFlags.idempotencyKey,
      FlagSpecification(
        key: "recordedAt",
        name: "--recorded-at",
        kind: .string,
        summary: "Recorded-at timestamp for the decision event.",
        valueName: "<iso>",
      ),
    ],
    subrow: "4e",
  )

  static let pause = CommandSpecification(
    unportedPath: ["showcase", "pause"],
    command: "showcase.pause",
    summary: "Pause a showcase run.",
    flags: [
      CommonFlags.repository,
      CommonFlags.dataRoot,
      CommonFlags.component,
      CommonFlags.json,
      ShowcaseFlags.run,
      FlagSpecification(
        key: "reason",
        name: "--reason",
        kind: .string,
        summary: "Pause reason (defaults to 'Paused by operator.').",
        valueName: "<text>",
      ),
      ShowcaseFlags.actor,
      ShowcaseFlags.idempotencyKey,
      FlagSpecification(
        key: "recordedAt",
        name: "--recorded-at",
        kind: .string,
        summary: "Recorded-at timestamp for the pause event.",
        valueName: "<iso>",
      ),
    ],
    subrow: "4e",
  )

  static let resume = CommandSpecification(
    unportedPath: ["showcase", "resume"],
    command: "showcase.resume",
    summary: "Resume a paused showcase run.",
    flags: [
      CommonFlags.repository,
      CommonFlags.dataRoot,
      CommonFlags.component,
      CommonFlags.json,
      ShowcaseFlags.run,
      FlagSpecification(
        key: "reason",
        name: "--reason",
        kind: .string,
        summary: "Resume reason (defaults to 'Resumed by operator.').",
        valueName: "<text>",
      ),
      ShowcaseFlags.actor,
      ShowcaseFlags.idempotencyKey,
      FlagSpecification(
        key: "recordedAt",
        name: "--recorded-at",
        kind: .string,
        summary: "Recorded-at timestamp for the resume event.",
        valueName: "<iso>",
      ),
    ],
    subrow: "4e",
  )

  static let finish = CommandSpecification(
    unportedPath: ["showcase", "finish"],
    command: "showcase.finish",
    summary: "Finish a showcase run.",
    flags: [
      CommonFlags.repository,
      CommonFlags.dataRoot,
      CommonFlags.component,
      CommonFlags.json,
      ShowcaseFlags.run,
      ShowcaseFlags.idempotencyKey,
      FlagSpecification(
        key: "recordedAt",
        name: "--recorded-at",
        kind: .string,
        summary: "Recorded-at timestamp for the finish event.",
        valueName: "<iso>",
      ),
    ],
    subrow: "4e",
  )
}
